version: '3'
services:
  tabby:
    command: 'serve --model TabbyML/StarCoder-1B --device cuda'
    image: tabbyml/tabby
    volumes:
      - data:/data
    environment:
      - HTTP_PROXY=http://192.168.30.10:7890
      - HTTPS_PROXY=http://192.168.30.10:7890
    ports:
      - '8080:8080'
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [ gpu ]


volumes:
  data: