version: '3'
services:
  opensearch:
    image: opensearchproject/opensearch
    ports:
      - "9200:9200"
      - "9600:9600"
    volumes:
      - data:/usr/share/opensearch/data
    environment:
      - discovery.type=single-node

volumes:
  data: