version: '3'

services:
  etcd:
    image: bitnami/etcd
    ports:
      - "2379:2379"
      - "2380:2380"
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
    volumes:
      - data:/bitnami/etcd

volumes:
  data:
