version: "3"
services:
  windows:
    image: registry.cn-hangzhou.aliyuncs.com/jaign-mirror/default:dockurr.windows
    container_name: windows
    devices:
      - /dev/kvm
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 13389:3389/tcp
      - 13389:3389/udp
    volumes:
      - "storage:/storage"
    stop_grace_period: 2m
    restart: on-failure
  
volumes:
  storage: