services:
  windows:
    image: dockurr/windows
    container_name: windows
    environment:
      VERSION: "11"
      LANGUAGE: "Chinese"
      REGION: "zh-CN"
      KEYBOARD: "zh-CN"
    devices:
      - /dev/kvm
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3390:3389/tcp
      - 3390:3389/udp
    stop_grace_period: 2m
    volumes:
      - "data:/storage"

volumes:
  data: