services:
  macos:
    image: dockurr/macos
    container_name: macos
    environment:
      VERSION: "13"
      # DISK_SIZE: "256G"
    devices:
      - /dev/kvm
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 5900:5900/tcp
      - 5900:5900/udp
    stop_grace_period: 2m
    volumes:
      - data:/storage

volumes:
  data:
